version: "3.8"

networks:
    ntalphash:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24

services:
    db:
        image: mysql:9.2
        restart: unless-stopped
        container_name: db
        volumes:
            - data-volume:/var/lib/mysql
        networks:
            ntalphash:
                ipv4_address: 172.20.0.2
        ports:
            - "3390:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-uroot",
                    "-p${DB_PASSWORD}",
                ]
            interval: 10s
            retries: 5
            start_period: 20s

    app:
        container_name: app
        build:
            context: ./app
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        depends_on:
            db:
                condition: service_healthy
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - DATABASE_URL=${DATABASE_URL}
        env_file:
            - ./.env
        networks:
            - ntalphash

volumes:
    data-volume:
